### ISSUE TITLE
Upload to board ?

### ISSUE THREAD

**Issue by charly37** [janjongboom/arduino-mbed-mashup#2]
Hi,

I wonder how do you upload the program you compile with mbed to the nano 33 board ?

Thx

**Comment by AlexanderKrampe** [comment]
Doesn't
mbed compile -m auto -t GCC_ARM -f
work?
 The -f option in particular should do it.

**Comment by janjongboom** [comment]
For the Nano 33 board just use the normal Arduino IDE to write and compile the code. You can use the Mbed libraries straight from there already (see https://blog.arduino.cc/2019/07/31/why-we-chose-to-build-the-arduino-nano-33-ble-core-on-mbed-os/). Nano 33 is not an Mbed-enabled development board so this project won't help.

**Comment by charly37** [comment]
Thx @AlexanderKrampe I was trying to do something similar to the command of the repo but with MBed UI but I think it is like online compiler and is not supported.
Thx @janjongboom. I was hoping there is a way to "flash" the nano 33 to be usable with Mbed when I saw this repository. I wonder if you have any "Mbed-enabled development board" based on the nRf 52840 to suggest ? I went with the Nano33 before realizing it may not works ;( I m noz checking these boards:
https://www.sparkfun.com/products/15025
https://www.adafruit.com/product/4062
https://www.seeedstudio.com/nRF52840-Micro-Development-Kit-p-3079.html
For my knowledge (if you have few minutes to explain) I wonder what need a board to have to be compliant with Mbed ? Do that comes from the bootloader it is ship with or do it also need some specific hardware ?

**Comment by janjongboom** [comment]
@charly37 The Nano 33 **is** compatible with Mbed, you just need to flash through the Arduino IDE. But all of Mbed is available there.

Probably if you build for nRF52-DK you'll get a working binary too, but I'm not sure of the clock settings on the Nano 33.

Otherwise nRF52-DK works fine.

**Comment by charly37** [comment]
Thx @janjongboom.
In the meantime I had some other people suggesting BOSSAC to do the upload:
https://github.com/arduino/ArduinoCore-nRF528x-mbedos/issues/19
Nevertheless I m curious to understand more by what you mean when you say "you just need to flash through the Arduino IDE" -> I was not aware of a way to have Arduino UI just doing the upload (or you mean copy my code to the UI and compile+upload) from it ?
